### ISSUE TITLE
关于搜索功能的BUG

### ISSUE THREAD

**Issue by DoubleBobCat** [CollegesChat/colleges.chat#34]
在搜索学校的时候会出现BUG
例如我输入“西南”，下面会出来一堆西南大学
但是如果我再加一个关键词，例如输入的是“西南石油”
即使刚刚出现了西南石油大学，这下也提示“没有找到符合条件的结果”
就算把学校名称打完也是这样

**Comment by Netrvin** [comment]
MkDocs 使用 Lunr.js 进行搜索，但 Lunr.js 不支持中文，因此可能会出现问题，该问题可能会在问卷及前端改版后解决
